name: Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - main # main 브랜치에 push가 발생하면 실행

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#       pages: write

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "22"

#       - name: Install Dependencies
#         run: npm ci

#       - name: Build
#         run: npm run build

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           personal_token: ${{ secrets.NAMEDAYNOTIFIER_TOKEN }} # personal_token 대신 GITHUB_TOKEN 사용
#           publish_branch: gh-pages
#           publish_dir: ./dist

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          force_orphan: true # 이전 배포 기록을 깨끗이 정리
